# Generated by Django 5.2.17 on 2026-09-22 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cartitem_cart_quantity_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('used_count__lte', models.F('usage_limit'))), name='coupon_usage_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_toman__gt', 0), ('total_toman__gt', 0)), name='order_amounts_positive'),
        ),
    ]
