# Generated by Django 5.2.17 on 2026-09-27 20:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_history(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderStatusHistory = apps.get_model('orders', 'OrderStatusHistory')
    OrderStatusHistory.objects.bulk_create([
        OrderStatusHistory(order_id=order_id, status=status)
        for order_id, status in Order.objects.values_list('id', 'status').iterator(chunk_size=1000)
    ], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_coupon_usage_within_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PROCESSING', 'در حال پردازش'), ('COMPLETED', 'تکمیل\u200cشده'), ('CANCELED', 'لغوشده'), ('FAILED', 'ناموفق'), ('REFUNDED', 'بازپرداخت\u200cشده')], default='PENDING', max_length=12),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PROCESSING', 'در حال پردازش'), ('COMPLETED', 'تکمیل\u200cشده'), ('CANCELED', 'لغوشده'), ('FAILED', 'ناموفق'), ('REFUNDED', 'بازپرداخت\u200cشده')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1de1d7_idx')],
            },
        ),
        migrations.RunPython(backfill_order_history, migrations.RunPython.noop),
    ]
