"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { EmptyState, LoadingState } from "@/components/states";
import { useAuth, useToast } from "@/contexts/app-context";
import { apiFetch, unwrapResults } from "@/lib/api";
import type { Paginated, Review, ReviewProductOption } from "@/lib/types";

export default function ReviewsPage() {
  const { user, loading: authLoading } = useAuth(); const router = useRouter(); const toast = useToast();
  const [products, setProducts] = useState<ReviewProductOption[]>([]); const [reviews, setReviews] = useState<Review[]>([]);
  const [product, setProduct] = useState(""); const [rating, setRating] = useState(5); const [body, setBody] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { if (!authLoading && !user) router.replace("/login?next=/reviews"); if (user) Promise.all([apiFetch<ReviewProductOption[]>("/reviews/eligible-products/"), apiFetch<Paginated<Review> | Review[]>("/reviews/?mine=1")]).then(([options, reviewData]) => { setProducts(options); setReviews(unwrapResults(reviewData)); }).catch((caught) => setError(caught instanceof Error ? caught.message : "خطا")).finally(() => setLoading(false)); }, [user, authLoading, router]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); try { const review = await apiFetch<Review>("/reviews/", { method:"POST", body:JSON.stringify({ product:Number(product), rating, body }) }); setReviews((current) => [review, ...current]); setProducts((current) => current.filter((item) => item.id !== Number(product))); setProduct(""); setBody(""); toast("نظر شما برای بررسی ثبت شد"); } catch (caught) { setError(caught instanceof Error ? caught.message : "ثبت نظر انجام نشد"); } };
  if (authLoading || loading) return <div className="container section"><LoadingState /></div>;
  return <div className="container section"><div className="section-head"><div><h1>نظرهای من</h1><p>فقط خریدهای تکمیل‌شده قابل ثبت نظر هستند.</p></div></div><div className="checkout-layout"><div>{reviews.length ? <div className="list">{reviews.map((review) => <div className="list-card" key={review.id}><div><h3>محصول شماره {review.product}</h3><p>{review.body}</p></div><span className="status">{review.status === "APPROVED" ? "تأییدشده" : review.status === "REJECTED" ? "ردشده" : "در انتظار بررسی"} · {"★".repeat(review.rating)}</span></div>)}</div> : <EmptyState title="نظری ثبت نشده" text="بعد از تکمیل خرید می‌توانید تجربه خود را ثبت کنید." />}</div><form className="panel stack" onSubmit={submit}><h2>ثبت نظر جدید</h2><div className="field"><label>محصول خریداری‌شده</label><select className="input" value={product} onChange={(event) => setProduct(event.target.value)} required><option value="">انتخاب کنید</option>{products.map((item) => <option value={item.id} key={item.id}>{item.title_fa}</option>)}</select></div><div className="field"><label>امتیاز</label><select className="input" value={rating} onChange={(event) => setRating(Number(event.target.value))}>{[5,4,3,2,1].map((value) => <option value={value} key={value}>{value} ستاره</option>)}</select></div><textarea className="input" minLength={3} maxLength={2000} value={body} onChange={(event) => setBody(event.target.value)} required />{error && <div className="alert error">{error}</div>}<button className="button" disabled={!products.length}>ثبت برای بررسی</button></form></div></div>;
}
