"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { EmptyState, LoadingState } from "@/components/states";
import { useAuth, useToast } from "@/contexts/app-context";
import { apiFetch, unwrapResults } from "@/lib/api";
import type { Paginated, Review, ReviewProductOption } from "@/lib/types";

export default function ReviewsPage() {
  const { user, loading: authLoading } = useAuth(); const router = useRouter(); const toast = useToast();
  const [products, setProducts] = useState<ReviewProductOption[]>([]); const [reviews, setReviews] = useState<Review[]>([]);
  const [product, setProduct] = useState(""); const [rating, setRating] = useState(5); const [body, setBody] = useState(""); const [editing, setEditing] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { if (!authLoading && !user) router.replace("/login?next=/reviews"); if (user) Promise.all([apiFetch<ReviewProductOption[]>("/reviews/eligible-products/"), apiFetch<Paginated<Review> | Review[]>("/reviews/?mine=1")]).then(([options, reviewData]) => { setProducts(options); setReviews(unwrapResults(reviewData)); }).catch((caught) => setError(caught instanceof Error ? caught.message : "خطا")).finally(() => setLoading(false)); }, [user, authLoading, router]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); try { const payload={ product:Number(product), rating, body }; const review = await apiFetch<Review>(editing ? `/reviews/${editing}/` : "/reviews/", { method:editing ? "PATCH" : "POST", body:JSON.stringify(payload) }); setReviews((current) => editing ? current.map((item)=>item.id===editing?review:item) : [review,...current]); if (!editing) setProducts((current) => current.filter((item) => item.id !== Number(product))); setProduct(""); setBody(""); setRating(5); setEditing(null); toast(editing ? "نظر ویرایش و برای بررسی ارسال شد" : "نظر شما برای بررسی ثبت شد"); } catch (caught) { setError(caught instanceof Error ? caught.message : "ثبت نظر انجام نشد"); } };
  const edit = (review:Review) => { setEditing(review.id); setProduct(String(review.product)); setRating(review.rating); setBody(review.body); window.scrollTo({ top:0, behavior:"smooth" }); };
  const remove = async (review:Review) => { if (!window.confirm("این نظر حذف شود؟")) return; try { await apiFetch(`/reviews/${review.id}/`, { method:"DELETE" }); setReviews((current)=>current.filter((item)=>item.id!==review.id)); setProducts((current)=>[...current,{ id:review.product, title_fa:review.product_title, slug:review.product_slug }]); toast("نظر حذف شد"); } catch (caught) { toast(caught instanceof Error ? caught.message : "حذف نظر انجام نشد"); } };
  if (authLoading || loading) return <div className="container section"><LoadingState /></div>;
  return <div className="container page-shell"><div className="section-head"><div><span className="eyebrow">تجربه خرید</span><h1>نظرهای من</h1><p>فقط محصولات خریداری‌شده قابل ثبت نظر هستند.</p></div></div><div className="checkout-layout"><div>{reviews.length ? <div className="list">{reviews.map((review) => <article className="review-manage-card" key={review.id}><div><h3>{review.product_title}</h3><span className={`status ${review.status}`}>{review.status === "APPROVED" ? "تأییدشده" : review.status === "REJECTED" ? "ردشده" : "در انتظار بررسی"}</span><p>{review.body}</p><b className="rating">{"★".repeat(review.rating)}</b></div><div className="review-actions"><button className="button ghost small" onClick={()=>edit(review)}>ویرایش</button><button className="button danger small" onClick={()=>void remove(review)}>حذف</button></div></article>)}</div> : <EmptyState title="نظری ثبت نشده" text="بعد از تکمیل خرید می‌توانید تجربه خود را ثبت کنید." />}</div><form className="panel stack" onSubmit={submit}><h2>{editing ? "ویرایش نظر" : "ثبت نظر جدید"}</h2><div className="field"><label>محصول خریداری‌شده</label><select className="input" value={product} onChange={(event) => setProduct(event.target.value)} required disabled={Boolean(editing)}><option value="">انتخاب کنید</option>{editing && reviews.filter((item)=>item.id===editing).map((item)=><option value={item.product} key={item.product}>{item.product_title}</option>)}{products.map((item) => <option value={item.id} key={item.id}>{item.title_fa}</option>)}</select></div><div className="field"><label>امتیاز</label><select className="input" value={rating} onChange={(event) => setRating(Number(event.target.value))}>{[5,4,3,2,1].map((value) => <option value={value} key={value}>{value} ستاره</option>)}</select></div><textarea className="input" aria-label="متن نظر" placeholder="تجربه خرید خود را بنویسید..." minLength={3} maxLength={2000} value={body} onChange={(event) => setBody(event.target.value)} required />{error && <div className="alert error">{error}</div>}<button className="button" disabled={!editing && !products.length}>{editing ? "ذخیره و ارسال مجدد" : "ثبت برای بررسی"}</button>{editing && <button type="button" className="button ghost" onClick={()=>{setEditing(null);setProduct("");setBody("");setRating(5);}}>انصراف</button>}</form></div></div>;
}
