"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { EmptyState, LoadingState } from "@/components/states";
import { Icon, PageIntro, StatusPill } from "@/components/ui";
import { useAuth, useCart } from "@/contexts/app-context";
import { apiFetch } from "@/lib/api";
import { formatToman, toPersianDigits } from "@/lib/format";
import type { Order, Payment } from "@/lib/types";

function stableKey(name: string) { const saved = sessionStorage.getItem(name); if (saved) return saved; const key = `${name}-${crypto.randomUUID()}`; sessionStorage.setItem(name, key); return key; }
export default function CheckoutPage() {
  const { user, loading: authLoading } = useAuth(); const { items, total, clearLocalCart } = useCart(); const [coupon, setCoupon] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  useEffect(() => { if (!authLoading && !user) router.replace("/login?next=/checkout"); }, [authLoading, user, router]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const order = await apiFetch<Order>("/orders/checkout/", { method:"POST", headers:{ "Idempotency-Key":stableKey("checkout") }, body:JSON.stringify({ coupon_code:coupon }) }); const payment = await apiFetch<{ payment:Payment; payment_url:string }>("/payments/initiate/", { method:"POST", body:JSON.stringify({ order_id:order.id, idempotency_key:stableKey(`payment-${order.id}`) }) }); clearLocalCart(); sessionStorage.removeItem("checkout"); window.location.assign(payment.payment_url); } catch (caught) { setError(caught instanceof Error ? caught.message : "ثبت سفارش انجام نشد"); } finally { setLoading(false); } };
  if (authLoading || !user) return <div className="container page-shell"><LoadingState/></div>; if (!items.length) return <div className="container page-shell"><EmptyState title="سبد خالی است" text="برای پرداخت ابتدا محصولی به سبد اضافه کن." href="/products" action="مشاهده محصولات"/></div>;
  return <div className="container page-shell"><PageIntro eyebrow="تکمیل خرید" title="ثبت سفارش و پرداخت" description="سفارش دیجیتال است؛ پس از تأیید پرداخت، کد در جزئیات سفارش نمایش داده می‌شود."/><div className="checkout-steps"><span className="done"><b><Icon name="check" size={14}/></b> سبد خرید</span><i/><span className="active"><b>۲</b> ثبت سفارش</span><i/><span><b>۳</b> دریافت کد</span></div><form className="checkout-layout" onSubmit={submit}><section className="checkout-content"><div className="checkout-card"><div className="checkout-card-head"><span className="icon-box"><Icon name="user"/></span><div><h2>اطلاعات خریدار</h2><p>کدها فقط در حساب همین شماره نمایش داده می‌شوند.</p></div></div><div className="buyer-row"><div><small>شماره موبایل</small><b dir="ltr">{user.phone_number}</b></div><StatusPill tone="success"><Icon name="check" size={14}/> تأییدشده</StatusPill></div></div><div className="checkout-card"><div className="checkout-card-head"><span className="icon-box"><Icon name="ticket"/></span><div><h2>کد تخفیف</h2><p>در صورت داشتن کد، قبل از پرداخت وارد کن.</p></div></div><div className="coupon-row"><input className="input" value={coupon} onChange={(event) => setCoupon(event.target.value.trim().toUpperCase())} placeholder="کد تخفیف"/><span>اعمال خودکار هنگام ثبت سفارش</span></div></div><div className="checkout-card"><div className="checkout-card-head"><span className="icon-box"><Icon name="wallet"/></span><div><h2>روش پرداخت</h2><p>پرداخت امن از طریق درگاه فعال فروشگاه</p></div></div><label className="payment-method selected"><input type="radio" checked readOnly/><span className="radio-dot"/><div><b>پرداخت آنلاین</b><small>انتقال امن و بازگشت خودکار به نتیجه سفارش</small></div><Icon name="shield"/></label></div>{error && <div className="alert error"><Icon name="x"/><span>{error}</span></div>}</section><aside className="order-summary"><h2>خلاصه نهایی</h2><div className="checkout-products">{items.map((item) => <div key={item.id}><span>{item.product_title}<small>{item.variant_label} × {toPersianDigits(item.quantity)}</small></span><b>{formatToman(item.price_toman * item.quantity)}</b></div>)}</div><div className="summary-row"><span>جمع محصولات</span><b>{formatToman(total)}</b></div><div className="summary-row"><span>تحویل دیجیتال</span><b className="success-text">رایگان</b></div><div className="summary-total"><span>مبلغ فعلی</span><strong>{formatToman(total)}</strong></div><button className="button primary full large" disabled={loading}>{loading ? <><span className="button-spinner"/> در حال ساخت پرداخت...</> : <>پرداخت و دریافت کد <Icon name="arrow-left"/></>}</button><p className="summary-caption"><Icon name="shield" size={15}/> با ثبت سفارش، موجودی برای مدت محدود رزرو می‌شود.</p></aside></form></div>;
}
