"use client";
import { FormEvent, useEffect, useState } from "react";
import { ProductCard } from "@/components/product-card";
import { EmptyState, ErrorState, LoadingState } from "@/components/states";
import { apiFetch, unwrapResults } from "@/lib/api";
import type { Brand, Category, Paginated, Product } from "@/lib/types";

export default function ProductsPage() {
  const [data, setData] = useState<Paginated<Product>>({ count:0, next:null, previous:null, results:[] }); const [categories, setCategories] = useState<Category[]>([]); const [brands, setBrands] = useState<Brand[]>([]);
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [brand, setBrand] = useState(""); const [ordering, setOrdering] = useState("-created_at"); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async (nextPage = page) => { setLoading(true); setError(""); const params = new URLSearchParams({ page:String(nextPage), ordering }); if (search) params.set("search", search); if (category) params.set("category__slug", category); if (brand) params.set("brand__slug", brand); try { setData(await apiFetch<Paginated<Product>>(`/catalog/products/?${params}`)); setPage(nextPage); } catch (caught) { setError(caught instanceof Error ? caught.message : "خطا"); } finally { setLoading(false); } };
  useEffect(() => { void load(1); Promise.all([apiFetch<Category[] | Paginated<Category>>("/catalog/categories/"), apiFetch<Brand[] | Paginated<Brand>>("/catalog/brands/")]).then(([cats, brs]) => { setCategories(unwrapResults(cats)); setBrands(unwrapResults(brs)); }).catch(() => undefined); }, []);
  const submit = (event: FormEvent) => { event.preventDefault(); void load(1); };
  return <div className="container section"><div className="section-head"><div><h1>فروشگاه</h1><p>{data.count} محصول برای انتخاب</p></div></div><form className="filters" onSubmit={submit}><input className="input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="نام محصول یا SKU..." /><select className="input" value={category} onChange={(event) => setCategory(event.target.value)}><option value="">همه دسته‌ها</option>{categories.map((item) => <option value={item.slug} key={item.id}>{item.title_fa}</option>)}</select><select className="input" value={brand} onChange={(event) => setBrand(event.target.value)}><option value="">همه برندها</option>{brands.map((item) => <option value={item.slug} key={item.id}>{item.title_fa}</option>)}</select><select className="input" value={ordering} onChange={(event) => setOrdering(event.target.value)}><option value="-created_at">جدیدترین</option><option value="title_fa">نام محصول</option></select><button className="button">اعمال</button></form>{loading ? <LoadingState /> : error ? <ErrorState message={error} retry={() => void load()} /> : data.results.length ? <><div className="product-grid">{data.results.map((product) => <ProductCard product={product} key={product.id} />)}</div><div className="pagination"><button className="button secondary" disabled={!data.previous} onClick={() => void load(page - 1)}>صفحه قبل</button><span>صفحه {page}</span><button className="button secondary" disabled={!data.next} onClick={() => void load(page + 1)}>صفحه بعد</button></div></> : <EmptyState title="محصولی پیدا نشد" text="فیلترها را تغییر دهید." />}</div>;
}
