"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { LoadingState } from "@/components/states";
import { Icon, PageIntro, StatusPill } from "@/components/ui";
import { useAuth, useToast } from "@/contexts/app-context";
import { apiFetch, unwrapResults } from "@/lib/api";
import { formatToman, toPersianDigits } from "@/lib/format";
import type { Order, Paginated, Profile, Review, Ticket } from "@/lib/types";

export default function AccountPage() {
  const { user, loading, refreshUser } = useAuth(); const toast = useToast(); const router = useRouter(); const [profile, setProfile] = useState<Profile>({ first_name:"", last_name:"", email:"" }); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [stats, setStats] = useState({ orders:0, completed:0, spent:0, tickets:0, reviews:0 });
  useEffect(() => { if (!loading && !user) router.replace("/login?next=/account"); if (user?.profile) setProfile(user.profile); if (user) Promise.all([apiFetch<Paginated<Order> | Order[]>("/orders/"), apiFetch<Paginated<Ticket> | Ticket[]>("/support/tickets/"), apiFetch<Paginated<Review> | Review[]>("/reviews/?mine=1")]).then(([orderData,ticketData,reviewData]) => { const orders=unwrapResults(orderData); setStats({ orders:orders.length, completed:orders.filter((item)=>item.status==="COMPLETED").length, spent:orders.filter((item)=>item.status==="COMPLETED").reduce((sum,item)=>sum+item.total_toman,0), tickets:unwrapResults(ticketData).filter((item)=>item.status!=="CLOSED").length, reviews:unwrapResults(reviewData).length }); }).catch(()=>undefined); }, [loading, user, router]);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { await apiFetch<Profile>("/auth/profile/", { method:"PATCH", body:JSON.stringify(profile) }); await refreshUser(); toast("پروفایل ذخیره شد"); } catch (caught) { setError(caught instanceof Error ? caught.message : "ذخیره انجام نشد"); } finally { setSaving(false); } };
  if (loading || !user) return <div className="container section"><LoadingState /></div>;
  return <div className="container page-shell"><PageIntro eyebrow="پنل کاربری" title={`سلام ${profile.first_name || "دوست عزیز"}`} description="سفارش‌ها، پشتیبانی، نظرها و اطلاعات حساب را از این صفحه مدیریت کن." action={<StatusPill tone="success"><Icon name="shield" size={14}/> حساب تأییدشده</StatusPill>}/><div className="account-stats"><div><Icon name="bag"/><b>{toPersianDigits(stats.orders)}</b><small>کل سفارش‌ها</small></div><div><Icon name="check"/><b>{toPersianDigits(stats.completed)}</b><small>خرید موفق</small></div><div><Icon name="wallet"/><b>{formatToman(stats.spent)}</b><small>مجموع خرید</small></div><div><Icon name="headset"/><b>{toPersianDigits(stats.tickets)}</b><small>تیکت باز</small></div></div><div className="account-layout"><aside className="account-menu"><div className="account-identity"><span className="review-avatar">{(profile.first_name || user.phone_number).slice(0,1)}</span><div><b>{profile.first_name ? `${profile.first_name} ${profile.last_name}` : "کاربر فروشگاه"}</b><small dir="ltr">{user.phone_number}</small></div></div><Link href="/orders"><Icon name="bag"/> سفارش‌های من</Link><Link href="/reviews"><Icon name="star"/> نظرهای من <small>{toPersianDigits(stats.reviews)}</small></Link><Link href="/tickets"><Icon name="headset"/> پشتیبانی</Link><Link href="/products"><Icon name="sparkles"/> ادامه خرید</Link></aside><form className="panel stack account-profile" onSubmit={save}><div><span className="eyebrow">اطلاعات حساب</span><h2>پروفایل شخصی</h2><p className="muted">اطلاعات صحیح برای پشتیبانی بهتر سفارش‌ها استفاده می‌شود.</p></div><div className="profile-grid"><div className="field"><label>نام</label><input className="input" value={profile.first_name} onChange={(e) => setProfile({ ...profile, first_name:e.target.value })} /></div><div className="field"><label>نام خانوادگی</label><input className="input" value={profile.last_name} onChange={(e) => setProfile({ ...profile, last_name:e.target.value })} /></div></div><div className="field"><label>ایمیل</label><input className="input" type="email" dir="ltr" placeholder="name@example.com" value={profile.email} onChange={(e) => setProfile({ ...profile, email:e.target.value })} /></div><div className="field"><label>شماره موبایل</label><input className="input" dir="ltr" value={user.phone_number} disabled /></div>{error && <div className="alert error">{error}</div>}<button className="button" disabled={saving}>{saving ? "در حال ذخیره..." : "ذخیره تغییرات"}</button></form></div></div>;
}
