# Generated by Django 5.2.17 on 2026-09-21 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(default='zarinpal', max_length=20)),
                ('idempotency_key', models.CharField(max_length=80)),
                ('authority', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount_toman', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('INITIATING', 'در حال درخواست'), ('READY', 'در انتظار پرداخت'), ('VERIFIED', 'تاییدشده'), ('FAILED', 'ناموفق'), ('RECONCILIATION', 'نیازمند بررسی/استرداد')], default='INITIATING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('gateway_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.paymenttransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_ed562a_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(fields=('order', 'idempotency_key'), name='payment_order_idempotency'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_a3a0f0_idx'),
        ),
    ]
