# Generated by Django 5.2.17 on 2026-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cartitem_cart_quantity_positive_and_more'),
        ('payments', '0002_paymentrefund'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_toman__gt', 0)), name='payment_amount_positive'),
        ),
    ]
