# Generated by Django 5.2.17 on 2026-09-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_payload', models.BinaryField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'موجود'), ('RESERVED', 'رزرو'), ('SOLD', 'فروخته\u200cشده')], default='AVAILABLE', max_length=10)),
            ],
        ),
    ]
