# Generated by Django 5.2.17 on 2026-09-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalitem',
            name='reserved_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_codes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='digitalitem',
            name='sold_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='digitalitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_items', to='catalog.productvariant'),
        ),
        migrations.AddIndex(
            model_name='digitalitem',
            index=models.Index(fields=['variant', 'status', 'id'], name='inventory_d_variant_759ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalitem',
            index=models.Index(fields=['reserved_order', 'status'], name='inventory_d_reserve_83b28b_idx'),
        ),
        migrations.AddConstraint(
            model_name='digitalitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reserved_order__isnull', True), ('sold_order_item__isnull', True), ('status', 'AVAILABLE')), models.Q(('reserved_order__isnull', False), ('sold_order_item__isnull', True), ('status', 'RESERVED')), models.Q(('reserved_order__isnull', True), ('sold_order_item__isnull', False), ('status', 'SOLD')), _connector='OR'), name='digital_item_state_consistency'),
        ),
    ]
