# Generated by Django 5.2.17 on 2026-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('old_price_toman__isnull', True), ('old_price_toman__gt', models.F('price_toman')), _connector='OR'), name='variant_old_price_gt_current'),
        ),
    ]
